/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    google()
    mavenLocal()
}

dependencies {
    implementation("com.io7m.xom:xom:1.2.10")
    implementation("junit:junit:4.13.2")
//    testImplementation("org.junit.platform:junit-platform-launcher:1.7.2")
//    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
//    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
}

group = "ThinkJava"
version = "1.0-SNAPSHOT"
description = "ThinkJava"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
